### PR TITLE
fix(rsc): fix CSS HMR with `?url`

### LINKED ISSUE #772: HMR for CSS imported with `?url` is not working
### Related plugins

- [ ] [plugin-react](https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react)

- [ ] [plugin-react-swc](https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react-swc)

- [ ] [plugin-react-oxc](https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react-oxc)

- [x] [plugin-rsc](https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-rsc)

### Describe the bug

When importing CSS with `?url` and then rendering to a `link` element (or returning from a `links` function export from a route module in React Router Framework Mode, but I'm reproducing this at a lower level) styles are not updated when editing the CSS file.

### Reproduction

https://github.com/markdalgleish/vitejs-plugin-rsc-css-url-hmr-issue-reproduction

### Steps to reproduce

1. `pnpm install`
2. `pnpm dev`
3. Open http://localhost:5173 in the browser
4. Edit `src/test-server.css` and `src/test-client.css`

Changes should be reflected in the browser immediately, but instead require a full page reload.

### System Info

```shell
System:
    OS: macOS 15.5
    CPU: (12) arm64 Apple M4 Pro
    Memory: 649.91 MB / 48.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 24.5.0 - ~/.nvm/versions/node/v24.5.0/bin/node
    npm: 11.5.1 - ~/.nvm/versions/node/v24.5.0/bin/npm
    pnpm: 10.8.0 - ~/Library/pnpm/pnpm
    bun: 1.0.1 - ~/.bun/bin/bun
  Browsers:
    Chrome: 139.0.7258.139
    Edge: 139.0.3405.111
    Firefox Nightly: 122.0a1
    Safari: 18.5
  npmPackages:
    @vitejs/plugin-react: latest => 5.0.1 
    @vitejs/plugin-rsc: latest => 0.4.23 
    vite: ^7.1.2 => 7.1.3
```

### Used Package Manager

pnpm

### Logs

_No response_

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vite.dev/guide).
- [x] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this is a Vite issue and not a framework-specific issue.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vite.dev/).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by hi-ogawa**
### Description

- Closes https://github.com/vitejs/vite-plugin-react/issues/772

TODO
- [x] fix client
- [x] fix server
- [x] test

### CODE REVIEW

File: packages/plugin-rsc/src/plugin.ts [hunk 1]
```diff
@@ -481,7 +481,9 @@ export default function vitePluginRsc(
           if (this.environment.name === 'client') {
             // filter out `.css?direct` (injected by SSR) to avoid browser full reload
             // when changing non-self accepting css such as `module.css`.
-            return ctx.modules.filter((m) => !m.id?.includes('?direct'))
+            return ctx.modules.filter(
+              (m) => !(m.id?.includes('?direct') && !m.isSelfAccepting),
+            )
```
Comment (hi-ogawa) [inline packages/plugin-rsc/src/plugin.ts:486]: Fixed by targeting non self-accepting case specifically. This likely means HMR doesn't work for `xxx.module.css?url`, but let's just postpone dealing with that edge case.
