### PR TITLE
fix(rsc): inject `AsyncLocalStorage` global via transform

### LINKED ISSUE #784: inject `AsyncLocalStorage` properly on non runnable environment
Instead of injecting global from plugin (during dev), we can probably transform react files directly, so that it covers cloudflare runtime.

https://github.com/vitejs/vite-plugin-react/blob/c719e5d97d9c70e29fc4a7a4f44c1abaa382a59e/packages/plugin-rsc/src/plugin.ts#L948-L955

### PR DESCRIPTION
**Pull request by hi-ogawa**
### Description

- Closes https://github.com/vitejs/vite-plugin-react/issues/784

In old days, we have externalized react on `ssr` environment, so it's not possible to inject through transform, but now it's possible.

### CODE REVIEW

File: packages/plugin-rsc/src/plugin.ts [hunk 1]
```diff
@@ -945,27 +947,28 @@ import.meta.hot.on("rsc:update", () => {
...
+            !code.includes('__viteRscAyncHooks')
+          ) {
+            // for build, we cannot use `import` as it confuses rollup commonjs plugin.
+            return (
+              (this.environment.mode === 'build' && !isRolldownVite
+                ? `const __viteRscAyncHooks = require("node:async_hooks");`
+                : `import * as __viteRscAyncHooks from "node:async_hooks";`) +
+              `globalThis.AsyncLocalStorage = __viteRscAyncHooks.AsyncLocalStorage;` +
+              code
+            )
```
Comment (hi-ogawa) [inline packages/plugin-rsc/src/plugin.ts:970]: Sadly, it feels as hacky as before, but probably alright.

File: packages/plugin-rsc/examples/ssg/vite.config.ts [hunk 2]
```diff
@@ -25,6 +25,14 @@ export default defineConfig((env) => ({
...
     rscSsgPlugin(),
   ],
+  environments: {
+    ssr: {
+      optimizeDeps: {
+        // TODO: move to plugin
+        include: ['react-dom/static.edge'],
+      },
+    },
+  },
```
Comment (hi-ogawa) [inline packages/plugin-rsc/examples/ssg/vite.config.ts]: Let's fix this first by https://github.com/vitejs/vite-plugin-react/pull/786

File: packages/plugin-rsc/src/plugin.ts (hunk 1 above)
Comment (StephaneMoyart) [reply packages/plugin-rsc/src/plugin.ts:970]: Hey, maybe you'd like to be warned about a little typo : __viteRscAyncHooks (should probably be __viteRscAsyncHooks)

Comment (hi-ogawa) [reply packages/plugin-rsc/src/plugin.ts:970]: Aha, good catch. PR welcome :)
