### PR TITLE
fix(react): respect tsconfig jsxImportSource by default

### LINKED ISSUE #719: plugin-react no longer respects `jsxImportSource` settings from tsconfig
### Related plugins

- [x] [plugin-react](https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react)

- [ ] [plugin-react-swc](https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react-swc)

- [ ] [plugin-react-oxc](https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react-oxc)

- [ ] [plugin-rsc](https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-rsc)

### Describe the bug

As of 5.0.0, it seems that the `jsxImportSource` setting in our tsconfig.json file is not being respected. Rather than getting the expected @emotion/react transform it just uses the default react transform, which means most of our styles are suddenly missing.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-1pz7rlsf?file=package.json

### Steps to reproduce

`npm i && npm run dev`

you can see that when using @vitejs/plugin-react@4.5.0 the demo works just fine and the text is red. when using 5.0.0 the text is black and in the devtools you can see a `css="[object Object]"` attribute, as the emotion jsx import is not being used and so the prop just gets passed through to the html.

### System Info

```shell
n/a
```

### Used Package Manager

pnpm

### Logs

<details>
<summary>Click to expand!</summary>

```shell
npm exec vite -- build --debug
  vite:config config file loaded in 223.72ms +0ms
  vite:env loading env files: [
  vite:env   '/home/projects/vitejs-vite-1pz7rlsf/.env',
  vite:env   '/home/projects/vitejs-vite-1pz7rlsf/.env.local',
  vite:env   '/home/projects/vitejs-vite-1pz7rlsf/.env.production',
  vite:env   '/home/projects/vitejs-vite-1pz7rlsf/.env.production.local'
  vite:env ] +0ms
  vite:env env files loaded in 0.74ms +1ms
  vite:env using resolved env: {} +0ms
  vite:config using resolved config: {
  vite:config   plugins: [
  vite:config     'vite:build-metadata',
  vite:config     'vite:watch-package-data',
  vite:config     'alias',
  vite:config     'vite:react-babel',
  vite:config     'vite:react-refresh',
  vite:config     'vite:modulepreload-polyfill',
  vite:config     'vite:resolve',
  vite:config     'vite:html-inline-proxy',
  vite:config     'vite:css',
  vite:config     'vite:esbuild',
  vite:config     'vite:json',
  vite:config     'vite:wasm-helper',
  vite:config     'vite:worker',
  vite:config     'vite:asset',
  vite:config     'vite:wasm-fallback',
  vite:config     'vite:define',
  vite:config     'vite:css-post',
  vite:config     'vite:build-html',
  vite:config     'vite:worker-import-meta-url',
  vite:config     'vite:asset-import-meta-url',
  vite:config     'vite:force-systemjs-wrap-complete',
  vite:config     'vite:prepare-out-dir',
  vite:config     'commonjs',
  vite:config     'vite:data-uri',
  vite:config     'vite:rollup-options-plugins',
  vite:config     'vite:dynamic-import-vars',
  vite:config     'vite:import-glob',
  vite:config     'vite:build-import-analysis',
  vite:config     'vite:esbuild-transpile',
  vite:config     'vite:terser',
  vite:config     'vite:manifest',
  vite:config     'vite:ssr-manifest',
  vite:config     'vite:reporter',
  vite:config     'vite:load-fallback'
  vite:config   ],
  vite:config   build: {
  vite:config     target: [ 'chrome107', 'edge107', 'firefox104', 'safari16' ],
  vite:config     polyfillModulePreload: true,
  vite:config     modulePreload: { polyfill: true },
  vite:config     outDir: 'dist',
  vite:config     assetsDir: 'assets',
  vite:config     assetsInlineLimit: 4096,
  vite:config     sourcemap: false,
  vite:config     terserOptions: {},
  vite:config     rollupOptions: { onwarn: [Function: onwarn] },
  vite:config     commonjsOptions: { include: [ /node_modules/ ], extensions: [ '.js', '.cjs' ] },
  vite:config     dynamicImportVarsOptions: { warnOnError: true, exclude: [ /node_modules/ ] },
  vite:config     write: true,
  vite:config     emptyOutDir: null,
  vite:config     copyPublicDir: true,
  vite:config     manifest: false,
  vite:config     lib: false,
  vite:config     ssrManifest: false,
  vite:config     ssrEmitAssets: false,
  vite:config     reportCompressedSize: true,
  vite:config     chunkSizeWarningLimit: 500,
  vite:config     watch: null,
  vite:config     cssCodeSplit: true,
  vite:config     minify: 'esbuild',
  vite:config     ssr: false,
  vite:config     emitAssets: true,
  vite:config     createEnvironment: [Function: createEnvironment],
  vite:config     cssTarget: [ 'chrome107', 'edge107', 'firefox104', 'safari16' ],
  vite:config     cssMinify: true
  vite:config   },
  vite:config   esbuild: { jsxDev: false, jsx: 'automatic', jsxImportSource: undefined },
  vite:config   optimizeDeps: {
  vite:config     include: [
  vite:config       'react',
  vite:config       'react-dom',
  vite:config       'react/jsx-dev-runtime',
  vite:config       'react/jsx-runtime'
  vite:config     ],
  vite:config     exclude: [],
  vite:config     needsInterop: [],
  vite:config     extensions: [],
  vite:config     disabled: undefined,
  vite:config     holdUntilCrawlEnd: true,
  vite:config     force: false,
  vite:config     noDiscovery: false,
  vite:config     esbuildOptions: { preserveSymlinks: false, jsx: 'automatic' }
  vite:config   },
  vite:config   resolve: {
  vite:config     externalConditions: [ 'node', 'module-sync' ],
  vite:config     extensions: [
  vite:config       '.mjs',  '.js',
  vite:config       '.mts',  '.ts',
  vite:config       '.jsx',  '.tsx',
  vite:config       '.json'
  vite:config     ],
  vite:config     dedupe: [ 'react', 'react-dom' ],
  vite:config     noExternal: [],
  vite:config     external: [],
  vite:config     preserveSymlinks: false,
  vite:config     alias: [
  vite:config       {
  vite:config         find: /^\/?@vite\/env/,
  vite:config         replacement: '/@fs/home/projects/vitejs-vite-1pz7rlsf/node_modules/vite/dist/client/env.mjs'
  vite:config       },
  vite:config       {
  vite:config         find: /^\/?@vite\/client/,
  vite:config         replacement: '/@fs/home/projects/vitejs-vite-1pz7rlsf/node_modules/vite/dist/client/client.mjs'
  vite:config       }
  vite:config     ],
  vite:config     mainFields: [ 'browser', 'module', 'jsnext:main', 'jsnext' ],
  vite:config     conditions: [ 'module', 'browser', 'development|production' ],
  vite:config     builtins: []
  vite:config   },
  vite:config   environments: {
  vite:config     client: {
  vite:config       define: undefined,
  vite:config       resolve: {
  vite:config         externalConditions: [ 'node', 'module-sync' ],
  vite:config         extensions: [
  vite:config           '.mjs',  '.js',
  vite:config           '.mts',  '.ts',
  vite:config           '.jsx',  '.tsx',
  vite:config           '.json'
  vite:config         ],
  vite:config         dedupe: [ 'react', 'react-dom' ],
  vite:config         noExternal: [],
  vite:config         external: [],
  vite:config         preserveSymlinks: false,
  vite:config         alias: [
  vite:config           {
  vite:config             find: /^\/?@vite\/env/,
  vite:config             replacement: '/@fs/home/projects/vitejs-vite-1pz7rlsf/node_modules/vite/dist/client/env.mjs'
  vite:config           },
  vite:config           {
  vite:config             find: /^\/?@vite\/client/,
  vite:config             replacement: '/@fs/home/projects/vitejs-vite-1pz7rlsf/node_modules/vite/dist/client/client.mjs'
  vite:config           }
  vite:config         ],
  vite:config         mainFields: [ 'browser', 'module', 'jsnext:main', 'jsnext' ],
  vite:config         conditions: [ 'module', 'browser', 'development|production' ],
  vite:config         builtins: []
  vite:config       },
  vite:config       keepProcessEnv: false,
  vite:config       consumer: 'client',
  vite:config       optimizeDeps: {
  vite:config         include: [
  vite:config           'react',
  vite:config           'react-dom',
  vite:config           'react/jsx-dev-runtime',
  vite:config           'react/jsx-runtime'
  vite:config         ],
  vite:config         exclude: [],
  vite:config         needsInterop: [],
  vite:config         extensions: [],
  vite:config         disabled: undefined,
  vite:config         holdUntilCrawlEnd: true,
  vite:config         force: false,
  vite:config         noDiscovery: false,
  vite:config         esbuildOptions: { preserveSymlinks: false, jsx: 'automatic' }
  vite:config       },
  vite:config       dev: {
  vite:config         warmup: [],
  vite:config         sourcemap: { js: true },
  vite:config         sourcemapIgnoreList: [Function: isInNodeModules],
  vite:config         preTransformRequests: true,
  vite:config         createEnvironment: [Function: defaultCreateClientDevEnvironment],
  vite:config         recoverable: true,
  vite:config         moduleRunnerTransform: false
  vite:config       },
  vite:config       build: {
  vite:config         target: [ 'chrome107', 'edge107', 'firefox104', 'safari16' ],
  vite:config         polyfillModulePreload: true,
  vite:config         modulePreload: { polyfill: true },
  vite:config         outDir: 'dist',
  vite:config         assetsDir: 'assets',
  vite:config         assetsInlineLimit: 4096,
  vite:config         sourcemap: false,
  vite:config         terserOptions: {},
  vite:config         rollupOptions: { onwarn: [Function: onwarn] },
  vite:config         commonjsOptions: { include: [ /node_modules/ ], extensions: [ '.js', '.cjs' ] },
  vite:config         dynamicImportVarsOptions: { warnOnError: true, exclude: [ /node_modules/ ] },
  vite:config         write: true,
  vite:config         emptyOutDir: null,
  vite:config         copyPublicDir: true,
  vite:config         manifest: false,
  vite:config         lib: false,
  vite:config         ssrManifest: false,
  vite:config         ssrEmitAssets: false,
  vite:config         reportCompressedSize: true,
  vite:config         chunkSizeWarningLimit: 500,
  vite:config         watch: null,
  vite:config         cssCodeSplit: true,
  vite:config         minify: 'esbuild',
  vite:config         ssr: false,
  vite:config         emitAssets: true,
  vite:config         createEnvironment: [Function: createEnvironment],
  vite:config         cssTarget: [ 'chrome107', 'edge107', 'firefox104', 'safari16' ],
  vite:config         cssMinify: true
  vite:config       },
  vite:config       plugins: [
  vite:config         {
  vite:config           name: 'vite:build-metadata',
  vite:config           renderChunk: [AsyncFunction: renderChunk]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:watch-package-data',
  vite:config           buildStart: [Function: buildStart],
  vite:config           buildEnd: [Function: buildEnd],
  vite:config           watchChange: [Function: watchChange]
  vite:config         },
  vite:config         {
  vite:config           name: 'alias',
  vite:config           buildStart: [AsyncFunction: buildStart],
  vite:config           resolveId: [Function: resolveId]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:react-babel',
  vite:config           enforce: 'pre',
  vite:config           config: [Function: config],
  vite:config           configResolved: [Function: configResolved],
  vite:config           options: [Function: options]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:react-refresh',
  vite:config           enforce: 'pre',
  vite:config           config: [Function: config],
  vite:config           resolveId: {
  vite:config             filter: { id: /^\/@react\-refresh$/ },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           load: {
  vite:config             filter: { id: /^\/@react\-refresh$/ },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           transformIndexHtml: [Function: transformIndexHtml]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:modulepreload-polyfill',
  vite:config           resolveId: {
  vite:config             filter: { id: /^vite\/modulepreload\-polyfill$/ },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           load: {
  vite:config             filter: { id: /^vite\/modulepreload\-polyfill\.js$/ },
  vite:config             handler: [Function: handler]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:resolve',
  vite:config           resolveId: {
  vite:config             filter: { id: { exclude: /^(?:\0|\/?virtual:)/ } },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           load: {
  vite:config             filter: {
  vite:config               id: [
  vite:config                 /^__vite\-browser\-external/,
  vite:config                 /^__vite\-optional\-peer\-dep/
  vite:config               ]
  vite:config             },
  vite:config             handler: [Function: handler]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:html-inline-proxy',
  vite:config           resolveId: {
  vite:config             filter: { id: /[?&]html-proxy\b/ },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           load: {
  vite:config             filter: { id: /[?&]html-proxy\b/ },
  vite:config             handler: [Function: handler]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:css',
  vite:config           buildStart: [Function: buildStart],
  vite:config           buildEnd: [Function: buildEnd],
  vite:config           load: {
  vite:config             filter: {
  vite:config               id: /\.(css|less|sass|scss|styl|stylus|pcss|postcss|sss)(?:$|\?)/
  vite:config             },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           transform: {
  vite:config             filter: {
  vite:config               id: {
  vite:config                 include: /\.(css|less|sass|scss|styl|stylus|pcss|postcss|sss)(?:$|\?)/,
  vite:config                 exclude: [
  vite:config                   /[?&]commonjs-proxy/,
  vite:config                   /[?&](?:worker|sharedworker|raw|url)\b/
  vite:config                 ]
  vite:config               }
  vite:config             },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:esbuild',
  vite:config           configureServer: [Function: configureServer],
  vite:config           transform: [AsyncFunction: transform]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:json',
  vite:config           transform: {
  vite:config             filter: {
  vite:config               id: {
  vite:config                 include: /\.json(?:$|\?)(?!commonjs-(?:proxy|external))/,
  vite:config                 exclude: /[?&](?:worker|sharedworker|raw|url)\b/
  vite:config               }
  vite:config             },
  vite:config             handler: [Function: handler]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:wasm-helper',
  vite:config           resolveId: {
  vite:config             filter: { id: /^vite\/wasm\-helper\.js$/ },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           load: {
  vite:config             filter: {
  vite:config               id: [
  vite:config                 /^vite\/wasm\-helper\.js$/,
  vite:config                 /(?<![?#].*)\.wasm\?init/
  vite:config               ]
  vite:config             },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:worker',
  vite:config           buildStart: [Function: buildStart],
  vite:config           load: {
  vite:config             filter: { id: /(?:\?|&)(worker|sharedworker)(?:&|$)/ },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           shouldTransformCachedModule: [Function: shouldTransformCachedModule],
  vite:config           transform: {
  vite:config             filter: { id: /(?:\?|&)worker_file&type=(\w+)(?:&|$)/ },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           renderChunk: [Function: renderChunk],
  vite:config           generateBundle: [Function: generateBundle]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:asset',
  vite:config           perEnvironmentStartEndDuringDev: true,
  vite:config           buildStart: [Function: buildStart],
  vite:config           resolveId: { handler: [Function: handler] },
  vite:config           load: {
  vite:config             filter: { id: { exclude: /^\0/ } },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           renderChunk: [Function: renderChunk],
  vite:config           generateBundle: [Function: generateBundle]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:wasm-fallback',
  vite:config           load: { filter: { id: /\.wasm$/ }, handler: [Function: handler] }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:define',
  vite:config           transform: { handler: [AsyncFunction: handler] }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:css-post',
  vite:config           renderStart: [Function: renderStart],
  vite:config           transform: {
  vite:config             filter: {
  vite:config               id: {
  vite:config                 include: /\.(css|less|sass|scss|styl|stylus|pcss|postcss|sss)(?:$|\?)/,
  vite:config                 exclude: [
  vite:config                   /[?&]commonjs-proxy/,
  vite:config                   /[?&](?:worker|sharedworker|raw|url)\b/
  vite:config                 ]
  vite:config               }
  vite:config             },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           renderChunk: [AsyncFunction: renderChunk],
  vite:config           augmentChunkHash: [Function: augmentChunkHash],
  vite:config           generateBundle: [AsyncFunction: generateBundle]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:build-html',
  vite:config           transform: {
  vite:config             filter: { id: /\.html$/ },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           generateBundle: [AsyncFunction: generateBundle]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:worker-import-meta-url',
  vite:config           applyToEnvironment: [Function: applyToEnvironment],
  vite:config           shouldTransformCachedModule: [Function: shouldTransformCachedModule],
  vite:config           transform: {
  vite:config             filter: {
  vite:config               code: /new\s+(?:Worker|SharedWorker)\s*\(\s*new\s+URL.+?import\.meta\.url/s
  vite:config             },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:asset-import-meta-url',
  vite:config           applyToEnvironment: [Function: applyToEnvironment],
  vite:config           transform: {
  vite:config             filter: {
  vite:config               id: {
  vite:config                 exclude: [
  vite:config                   /^vite\/preload\-helper\.js$/,
  vite:config                   /^\/home\/projects\/vitejs\-vite\-1pz7rlsf\/node_modules\/vite\/dist\/client\/client\.mjs$/
  vite:config                 ]
  vite:config               },
  vite:config               code: /new\s+URL.+import\.meta\.url/
  vite:config             },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:force-systemjs-wrap-complete',
  vite:config           renderChunk: [Function: renderChunk]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:prepare-out-dir',
  vite:config           options: [Function: options],
  vite:config           renderStart: { order: 'pre', handler: [Function: handler] }
  vite:config         },
  vite:config         {
  vite:config           name: 'commonjs',
  vite:config           version: '28.0.6',
  vite:config           options: [Function: options],
  vite:config           buildStart: [Function: buildStart],
  vite:config           buildEnd: [Function: buildEnd],
  vite:config           load: [AsyncFunction: load],
  vite:config           shouldTransformCachedModule: [Function: shouldTransformCachedModule],
  vite:config           transform: [Function: transform]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:data-uri',
  vite:config           buildStart: [Function: buildStart],
  vite:config           resolveId: [Function: resolveId],
  vite:config           load: [Function: load]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:dynamic-import-vars',
  vite:config           resolveId: {
  vite:config             filter: { id: /^vite\/dynamic\-import\-helper\.js$/ },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           load: {
  vite:config             filter: { id: /^vite\/dynamic\-import\-helper\.js$/ },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           transform: {
  vite:config             filter: {
  vite:config               id: {
  vite:config                 exclude: /^\/home\/projects\/vitejs\-vite\-1pz7rlsf\/node_modules\/vite\/dist\/client\/client\.mjs$/
  vite:config               },
  vite:config               code: /\bimport\s*[(/]/
  vite:config             },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           }
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:import-glob',
  vite:config           buildStart: [Function: buildStart],
  vite:config           transform: {
  vite:config             filter: { code: 'import.meta.glob' },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           hotUpdate: [Function: hotUpdate]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:build-import-analysis',
  vite:config           resolveId: {
  vite:config             filter: { id: /^vite\/preload\-helper\.js$/ },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           load: {
  vite:config             filter: { id: /^vite\/preload\-helper\.js$/ },
  vite:config             handler: [Function: handler]
  vite:config           },
  vite:config           transform: {
  vite:config             filter: { code: /import\s*\(/ },
  vite:config             handler: [AsyncFunction: handler]
  vite:config           },
  vite:config           renderChunk: [Function: renderChunk],
  vite:config           generateBundle: [Function: generateBundle]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:esbuild-transpile',
  vite:config           applyToEnvironment: [Function: applyToEnvironment],
  vite:config           renderChunk: [AsyncFunction: renderChunk]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:terser',
  vite:config           applyToEnvironment: [Function: applyToEnvironment],
  vite:config           renderChunk: [AsyncFunction: renderChunk],
  vite:config           closeBundle: [Function: closeBundle]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:reporter',
  vite:config           sharedDuringBuild: true,
  vite:config           perEnvironmentStartEndDuringDev: true,
  vite:config           transform: [Function: transform],
  vite:config           buildStart: [Function: buildStart],
  vite:config           buildEnd: [Function: buildEnd],
  vite:config           renderStart: [Function: renderStart],
  vite:config           renderChunk: [Function: renderChunk],
  vite:config           generateBundle: [Function: generateBundle],
  vite:config           writeBundle: [AsyncFunction: writeBundle]
  vite:config         },
  vite:config         {
  vite:config           name: 'vite:load-fallback',
  vite:config           load: { handler: [AsyncFunction: handler] }
  vite:config         }
  vite:config       ]
  vite:config     }
  vite:config   },
  vite:config   configFile: '/home/projects/vitejs-vite-1pz7rlsf/vite.config.ts',
  vite:config   configFileDependencies: [ '/home/projects/vitejs-vite-1pz7rlsf/vite.config.ts' ],
  vite:config   inlineConfig: {
  vite:config     root: undefined,
  vite:config     base: undefined,
  vite:config     mode: undefined,
  vite:config     configFile: undefined,
  vite:config     configLoader: undefined,
  vite:config     logLevel: undefined,
  vite:config     clearScreen: undefined,
  vite:config     build: {}
  vite:config   },
  vite:config   root: '/home/projects/vitejs-vite-1pz7rlsf',
  vite:config   base: '/',
  vite:config   decodedBase: '/',
  vite:config   rawBase: '/',
  vite:config   publicDir: '/home/projects/vitejs-vite-1pz7rlsf/public',
  vite:config   cacheDir: '/home/projects/vitejs-vite-1pz7rlsf/node_modules/.vite',
  vite:config   command: 'build',
  vite:config   mode: 'production',
  vite:config   isWorker: false,
  vite:config   mainConfig: null,
  vite:config   bundleChain: [],
  vite:config   isProduction: true,
  vite:config   css: {
  vite:config     transformer: 'postcss',
  vite:config     preprocessorMaxWorkers: true,
  vite:config     devSourcemap: false
  vite:config   },
  vite:config   json: { namedExports: true, stringify: 'auto' },
  vite:config   server: {
  vite:config     port: 5173,
  vite:config     strictPort: false,
  vite:config     host: undefined,
  vite:config     allowedHosts: [],
  vite:config     https: undefined,
  vite:config     open: false,
  vite:config     proxy: undefined,
  vite:config     cors: {
  vite:config       origin: /^https?:\/\/(?:(?:[^:]+\.)?localhost|127\.0\.0\.1|\[::1\])(?::\d+)?$/
  vite:config     },
  vite:config     headers: {},
  vite:config     warmup: { clientFiles: [], ssrFiles: [] },
  vite:config     middlewareMode: false,
  vite:config     fs: {
  vite:config       strict: true,
  vite:config       deny: [ '.env', '.env.*', '*.{crt,pem}', '**/.git/**' ],
  vite:config       allow: [ '/home/projects/vitejs-vite-1pz7rlsf' ]
  vite:config     },
  vite:config     preTransformRequests: true,
  vite:config     perEnvironmentStartEndDuringDev: false,
  vite:config     sourcemapIgnoreList: [Function: isInNodeModules]
  vite:config   },
  vite:config   builder: undefined,
  vite:config   preview: {
  vite:config     port: 4173,
  vite:config     strictPort: false,
  vite:config     host: undefined,
  vite:config     allowedHosts: [],
  vite:config     https: undefined,
  vite:config     open: false,
  vite:config     proxy: undefined,
  vite:config     cors: {
  vite:config       origin: /^https?:\/\/(?:(?:[^:]+\.)?localhost|127\.0\.0\.1|\[::1\])(?::\d+)?$/
  vite:config     },
  vite:config     headers: {}
  vite:config   },
  vite:config   envDir: '/home/projects/vitejs-vite-1pz7rlsf',
  vite:config   env: { BASE_URL: '/', MODE: 'production', DEV: false, PROD: true },
  vite:config   assetsInclude: [Function: assetsInclude],
  vite:config   logger: {
  vite:config     hasWarned: false,
  vite:config     info: [Function: info],
  vite:config     warn: [Function: warn],
  vite:config     warnOnce: [Function: warnOnce],
  vite:config     error: [Function: error],
  vite:config     clearScreen: [Function: clearScreen],
  vite:config     hasErrorLogged: [Function: hasErrorLogged]
  vite:config   },
  vite:config   packageCache: Map(1) {
  vite:config     'fnpd_/home/projects/vitejs-vite-1pz7rlsf' => {
  vite:config       dir: '/home/projects/vitejs-vite-1pz7rlsf',
  vite:config       data: {
  vite:config         name: 'vite-react-typescript-starter',
  vite:config         private: true,
  vite:config         version: '0.0.0',
  vite:config         type: 'module',
  vite:config         scripts: {
  vite:config           dev: 'vite',
  vite:config           build: 'tsc -b && vite build',
  vite:config           lint: 'eslint .',
  vite:config           preview: 'vite preview'
  vite:config         },
  vite:config         dependencies: { react: '^19.1.1', 'react-dom': '^19.1.1' },
  vite:config         devDependencies: {
  vite:config           '@emotion/react': '11.14.0',
  vite:config           '@types/react': '^19.1.10',
  vite:config           '@types/react-dom': '^19.1.7',
  vite:config           '@vitejs/plugin-react': '^4.5.0',
  vite:config           typescript: '~5.8.3',
  vite:config           vite: '^7.1.2'
  vite:config         }
  vite:config       },
  vite:config       hasSideEffects: [Function: hasSideEffects],
  vite:config       setResolvedCache: [Function: setResolvedCache],
  vite:config       getResolvedCache: [Function: getResolvedCache]
  vite:config     },
  vite:config     set: [Function (anonymous)]
  vite:config   },
  vite:config   worker: { format: 'iife', plugins: '() => plugins', rollupOptions: {} },
  vite:config   appType: 'spa',
  vite:config   experimental: {
  vite:config     importGlobRestoreExtension: false,
  vite:config     renderBuiltUrl: undefined,
  vite:config     hmrPartialAccept: false
  vite:config   },
  vite:config   future: undefined,
  vite:config   ssr: {
  vite:config     target: 'node',
  vite:config     optimizeDeps: { esbuildOptions: { preserveSymlinks: false } },
  vite:config     resolve: { conditions: undefined, externalConditions: undefined }
  vite:config   },
  vite:config   dev: {
  vite:config     warmup: [],
  vite:config     sourcemap: { js: true },
  vite:config     sourcemapIgnoreList: [Function: isInNodeModules],
  vite:config     preTransformRequests: false,
  vite:config     createEnvironment: [Function: defaultCreateDevEnvironment],
  vite:config     recoverable: false,
  vite:config     moduleRunnerTransform: false
  vite:config   },
  vite:config   webSocketToken: 'KHV3OqpY_vUT',
  vite:config   getSortedPlugins: [Function: getSortedPlugins],
  vite:config   getSortedPluginHooks: [Function: getSortedPluginHooks],
  vite:config   createResolver: [Function: createResolver],
  vite:config   fsDenyGlob: [Function: arrayMatcher],
  vite:config   safeModulePaths: Set(0) {},
  vite:config   [Symbol(vite:resolved-config)]: true
  vite:config } +8ms
vite v7.1.2 building for production...
✓ 57 modules transformed.
dist/index.html                   0.46 kB │ gzip:  0.30 kB
dist/assets/index-D8b4DHJx.css    1.39 kB │ gzip:  0.71 kB
dist/assets/index-CDBwk82u.js   206.42 kB │ gzip: 65.96 kB
✓ built in 969ms
```

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vite.dev/guide).
- [x] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this is a Vite issue and not a framework-specific issue.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vite.dev/).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by hi-ogawa**
### Description

- Closes https://github.com/vitejs/vite-plugin-react/issues/719
- Requires
  - https://github.com/vitejs/rolldown-vite/pull/376
  - https://github.com/rolldown/rolldown/pull/5771

### CODE REVIEW

File: packages/plugin-react/src/index.ts [hunk 1]
```diff
@@ -152,8 +152,7 @@ export default function viteReact(opts: Options = {}): Plugin[] {
           return {
             oxc: {
               jsx: {
-                runtime: 'automatic',
-                importSource: jsxImportSource,
```
Comment (hi-ogawa) [inline packages/plugin-react/src/index.ts]: I needed to remove `runtime` too since rolldown-vite merge oxc option with tsconfig only when `runtime === undefined`. Is this intended or allow also `runtime === 'automatic'`? @sapphi-red  https://github.com/vitejs/rolldown-vite/blob/f88cb05e755457fd9ea99174a017c49964510c3f/packages/vite/src/node/plugins/oxc.ts#L65-L68

Comment (ArnaudBarre) [reply packages/plugin-react/src/index.ts]: With the vite-rolldown code as is, this would mean that users having `jsx === 'preserve'` in tsconfig will now have broken apps I think. 
Is this also the same logic for the esbuild?

Comment (hi-ogawa) [reply packages/plugin-react/src/index.ts]: Ah, I didn't know react plugin is ensuring `automatic` so that tsconfig's jsx preserve will be ignored. Probably rolldown-vite oxc option merging needs to be tweaked. I'll also add that test case too then.

Comment (ArnaudBarre) [reply packages/plugin-react/src/index.ts]: > I didn't know react plugin is ensuring automatic so that tsconfig's jsx preserve will be ignored
I'm not sure it's a goal, but with the current implementation of vite-rolldown it happen to be the case.

**Comment by hi-ogawa** [comment]
`test-build` is failing because of native plugin https://github.com/vitejs/rolldown-vite/pull/376#issuecomment-3194854659

**Comment by sapphi-red** [comment]
@hi-ogawa I've released rolldown-vite v7.1.3, which includes the fixes.

File: playground/tsconfig/tsconfig.json [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+    "skipLibCheck": true,
+
+    /* Bundler mode */
+    "moduleResolution": "bundler",
+    "allowImportingTsExtensions": true,
+    "resolveJsonModule": true,
+    "isolatedModules": true,
+    "noEmit": true,
+    "jsx": "react-jsx",
+    "jsxImportSource": "@emotion/react",
```
Comment (ArnaudBarre) [inline playground/tsconfig/tsconfig.json:18]: Maybe we can update the playground/emotion to comment the manual jsxImportSource (saying we expect to be infered from tsconfig)

Comment (hi-ogawa) [reply playground/tsconfig/tsconfig.json:18]: Good idea. I should reuse that but I'm not sure how to get esbuild to pickup tsconfig for jsx. I'll update the example to tsx in a later PR and remove this one.
