### PR TITLE
fix(oxc): disable refresh transform when `server.hmr: false`

### LINKED ISSUE #500: Getting `$RefreshReg$ is not defined ` error when running tests with vitest and plugin-react-oxc
### Related plugins

- [ ] [plugin-react](https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react)

- [ ] [plugin-react-swc](https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react-swc)

- [x] [plugin-react-oxc](https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react-oxc)

### Describe the bug

After running simple Hello World app it is giving error -$RefreshReg$ is not defined and test case is failing. It is working fine with `plugin-react`.

FAIL  src/App.test.tsx [ src/App.test.tsx ]
ReferenceError: $RefreshReg$ is not defined
 ❯ src/App.tsx:9:1
      3| export default function App() {
      4|   return <>Hello World</>;
      5| }
       |  ^
      6|
 ❯ src/App.test.tsx:2:1

The App is running fine

Also there is warning while running test - 
Both esbuild and oxc options were set. oxc options will be used and esbuild options will be ignored.

Please feel free to close this bug if there is mistake in bug report

### Reproduction

https://stackblitz.com/edit/vitejs-vite-uqmfm78m?file=src%2FApp.test.tsx&view=editor

### Steps to reproduce

Run `npm install` followed by `npm t`

### System Info

```shell
NA
```

### Used Package Manager

npm

### Logs

_No response_

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vite.dev/guide).
- [x] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [x] Make sure this is a Vite issue and not a framework-specific issue.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vite.dev/).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by hi-ogawa**
### Description

- Closes https://github.com/vitejs/vite-plugin-react/issues/500

~I think another approach is to configure `oxc` instead of `esbuild` on Vitest side when `rolldown-vite` is detected. Probably it makes more sense since we should migrate from `esbuild` to `oxc` eventually anyways.~

~(Btw tests are failing because `process.env.VITEST` is true during `test-serve` e2e :upside_down_face:)~

So, technically this is not Vitest specific issue. The same error would happen when `server.hmr: false`.

### CODE REVIEW

**Comment by ArnaudBarre** [comment]
This issue with this way of configuring refresh is that we are enabling it for ssr too, but other plugins don't do it

**Comment by hi-ogawa** [comment]
Interesting point. It looks like rolldown-vite actually configures `refresh: false` in a delayed way for ssr https://github.com/vitejs/rolldown-vite/blob/52e24901d155515b3f30cfb877391e9851bb5497/packages/vite/src/node/plugins/oxc.ts#L332-L340

**Comment by ArnaudBarre** [comment]
Ok so we need to find a way to make the tests works now

**Comment by sapphi-red** [comment]
How about adding a plugin like below?
```js
  const viteConfigPost: Plugin = {
    name: 'vite:react-oxc:config',
    enforce: 'post',
    config(userConfig) {
      if (userConfig.oxc?.jsx && !userConfig.server.hmr) {
        userConfig.oxc.jsx.refresh = false
      }
    }
}
```

File: packages/plugin-react-oxc/src/index.ts [hunk 1]
```diff
@@ -82,6 +82,22 @@ export default function viteReact(opts: Options = {}): PluginOption[] {
     },
   }
 
+  const viteConfigPost: Plugin = {
+    name: 'vite:react-oxc:config-psot',
```
Comment (sapphi-red) [inline packages/plugin-react-oxc/src/index.ts]:
```suggestion
    name: 'vite:react-oxc:config-post',
```

**Review by sapphi-red — APPROVED** [review]

File: playground/hmr-false/__tests__/hmr-false.spec.ts [hunk 2]
```diff
@@ -0,0 +1,8 @@
+import { expect, test } from 'vitest'
+import { page } from '~utils'
+
+test('basic', async () => {
+  expect(await page.textContent('button')).toMatch('count is 0')
+  expect(await page.click('button'))
+  expect(await page.textContent('button')).toMatch('count is 1')
+})
```
Comment (ArnaudBarre) [inline playground/hmr-false/__tests__/hmr-false.spec.ts:8]: Can you add that for serve, edit to App.tsx does full page reload?

**Review by ArnaudBarre — APPROVED** [review]

File: playground/hmr-false/__tests__/hmr-false.spec.ts (hunk 2 above)
Comment (hi-ogawa) [reply playground/hmr-false/__tests__/hmr-false.spec.ts:8]: I was wondering about that too but it turns out `server.hmr: false` even disables full reload and test actually failed.

Comment (ArnaudBarre) [reply playground/hmr-false/__tests__/hmr-false.spec.ts:8]: Ok let's keep it like this!
