### PR TITLE
fix(react): refreshWrapper was injected twice for class components when using babel plugins and rolldown-vite

### LINKED ISSUE #368: rolldown-vite 7.1.0 and plugin-react 5.0.0 error with Class components when using react-compiler
### Describe the bug

Posted this on the discord but told to move it out to here.

Trying to migrate a fairly big work project over to rolldown-vite and am getting errors with plugin-react v5. I didn't have this problem in v4 so I assume it's something to do with adding OXC into the plugin

You may have to download the project from Stackblitz and run locally as the WASM version doesn't seem very happy.

When ran locally, the server boots, but if you open the page you'll see that there's a console error
```
Uncaught SyntaxError: Identifier 'RefreshRuntime' has already been declared
```

This has replaced a previous error that mentioned oxc compilation issues, that I cannot replicate now.

I have been highlighted that there might also be a related issue in the plugin-react repo https://github.com/vitejs/vite-plugin-react/issues/346

### Reproduction

https://stackblitz.com/edit/vitejs-vite-qifa3tcf?file=src%2Fmain.tsx

### Steps to reproduce

I have found that this only occurs when using react-compiler. Removing it from the babel plugins fixes the issue.

### System Info

```shell
System:
    OS: macOS 15.5
    CPU: (11) arm64 Apple M3 Pro
    Memory: 1.43 GB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.19.0 - ~/.volta/tools/image/node/20.19.0/bin/node
    Yarn: 3.2.4 - ~/Dev/Bots/portal/node_modules/.bin/yarn
    npm: 10.8.2 - ~/.volta/tools/image/node/20.19.0/bin/npm
    bun: 1.2.8 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 138.1.80.124
    Edge: 139.0.3405.86
    Safari: 18.5
  npmPackages:
    @vitejs/plugin-react: 5.0.0 => 5.0.0 
    rolldown-vite:  7.1.1
```

### Used Package Manager

yarn

### Logs

_No response_

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitejs/rolldown-vite/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitejs/rolldown-vite/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vite.dev/guide) and the [Rolldown-related guide](https://main.vite.dev/guide/rolldown.html).
- [x] Check that there isn't [already an issue](https://github.com/vitejs/rolldown-vite/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/rolldown-vite/discussions) or join our [Discord Chat Server](https://chat.vite.dev/).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by sapphi-red**
### Description

fixes https://github.com/vitejs/rolldown-vite/issues/368

### CODE REVIEW

File: packages/plugin-react/src/index.ts [hunk 1]
```diff
@@ -324,7 +324,8 @@ export default function viteReact(opts: Options = {}): Plugin[] {
         })
 
         if (result) {
-          if (!useFastRefresh) {
+          // refresh wrapper is added later for rolldown-vite
+          if (!useFastRefresh || isRolldownVite) {
```
Comment (hi-ogawa) [inline packages/plugin-react/src/index.ts]: Can we move this to `const useFastRefresh = !isRolldownVite && ...` above?

**Review by hi-ogawa — COMMENTED** [review]
Why did this happen only on class component?

**Comment by ArnaudBarre** [comment]
I need to look at it in details, because it means the host option is not respected then.
What was the initial reason for rolldown-vite to include framework specific hmr?

**Review by hi-ogawa — COMMENTED** [review]
> Why did this happen only on class component?

This condition `reactCompRE` was causing the first `addRefreshWrapper` during `vite:react-babel` to inject wrapper.

https://github.com/vitejs/vite-plugin-react/blob/275d2ee807f96bc8e79294df3f1ce1b65c0e8a0b/packages/common/refresh-utils.ts#L30

**Comment by hi-ogawa** [comment]
> I need to look at it in details, because it means the host option is not respected then. What was the initial reason for rolldown-vite to include framework specific hmr?

Rolldown-vite doesn't inject refresh "wrapper", but it only takes care of refresh "transform". Rolldown-vite still uses `vite:react:refresh-wrapper` plugin below and `addRefreshWrapper` during `vite:react-babel` was meant to be skipped (but it wasn't, thus bug).

Indeed, `reactRefreshHost` isn't passed to `vite:react:refresh-wrapper`, so that's also a separate bug.

**Review by hi-ogawa — APPROVED** [review]

**Comment by ArnaudBarre** [comment]
Thanks the condition after the update seems better for me!

**Review by Lokoak47 — APPROVED** [review]
